name: College Funding Consultants
favicon: null
layout_spectrum: 0.2446009311825037
typography_spectrum: 0.7955479447264224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10739238862879574
  lightness: 0.5840976792387664
  saturation: 0.12819810956716537
  rhythmicContrast: 0.5620472324080765
purpose: []
